version: "3.8"
services:
  rrr-app:
    build: .
    container_name: rrr-listing
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
